sudo: required
services:
  - docker
before_install:
  - docker build -t dstasaski/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "skipping tests"
#  - docker run dstasaski/react-test npm test -- --coverage
 
after_success:
  - docker build -t dstasaski/multi-client ./client
  - docker build -t dstasaski/multi-nginx ./nginx
  - docker build -t dstasaski/multi-server ./server
  - docker build -t dstasaski/multi-worker ./worker
# take images and push them to docker hub
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push dstasaski/multi-client
  - docker push dstasaski/multi-nginx
  - docker push dstasaski/multi-server
  - docker push dstasaski/multi-worker


